-- ===========================================
-- AI MODULE
-- Predictions, Anomalies, Alerts
-- ===========================================


-- ===========================================
-- 1. MODEL REGISTRY
-- Stores trained AI model information
-- ===========================================

CREATE TABLE model_registry (
    model_id SERIAL PRIMARY KEY,

    model_name VARCHAR(100) NOT NULL,

    model_type VARCHAR(50) NOT NULL,

    blob_storage_path TEXT,

    trained_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    metrics_json JSONB
);


-- ===========================================
-- 2. PREDICTIONS
-- Stores AI forecasting results
-- ===========================================

CREATE TABLE predictions (
    prediction_id SERIAL PRIMARY KEY,

    user_id VARCHAR(10) NOT NULL,

    model_id INTEGER NOT NULL,

    prediction_type VARCHAR(50) NOT NULL,

    category_id INTEGER,

    target_period DATE NOT NULL,

    predicted_value DECIMAL(12,2) NOT NULL,

    FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE,

    FOREIGN KEY (model_id)
        REFERENCES model_registry(model_id)
);


-- ===========================================
-- 3. ANOMALIES
-- Stores Autoencoder anomaly results
-- ===========================================

CREATE TABLE anomalies (
    anomaly_id SERIAL PRIMARY KEY,

    transaction_id INTEGER NOT NULL,

    model_id INTEGER NOT NULL,

    reconstruction_error DECIMAL(12,6) NOT NULL,

    is_anomaly BOOLEAN NOT NULL DEFAULT FALSE,

    FOREIGN KEY (transaction_id)
        REFERENCES transactions(transaction_id)
        ON DELETE CASCADE,

    FOREIGN KEY (model_id)
        REFERENCES model_registry(model_id)
);


-- ===========================================
-- 4. ALERTS
-- Stores warnings generated by the system
-- ===========================================

CREATE TABLE alerts (
    alert_id SERIAL PRIMARY KEY,

    user_id VARCHAR(10) NOT NULL,

    alert_type VARCHAR(50) NOT NULL,

    message TEXT NOT NULL,

    related_prediction_id INTEGER,

    severity VARCHAR(20) NOT NULL DEFAULT 'medium',

    FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE,

    FOREIGN KEY (related_prediction_id)
        REFERENCES predictions(prediction_id)
        ON DELETE SET NULL
);


-- ===========================================
-- 5. NOTIFICATIONS
-- Stores notification delivery information
-- ===========================================

CREATE TABLE notifications (
    notification_id SERIAL PRIMARY KEY,

    alert_id INTEGER NOT NULL,

    channel VARCHAR(20) NOT NULL,

    sent_at TIMESTAMP,

    read_at TIMESTAMP,

    FOREIGN KEY (alert_id)
        REFERENCES alerts(alert_id)
        ON DELETE CASCADE
);